# Book settings
title: Bed-1304 Python-lab
author: setternoeher
logo: img/py.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
  allow_errors: true
  exclude_patterns:
    - 'notebooks/00/intro.ipynb'
    - 'notebooks/01/introduksjon.ipynb'
    - 'notebooks/10/simulering.ipynb'

sphinx:
  config:
    nb_kernel_rgx_aliases:
      ".*": "python3"
    html_theme: "sphinx_book_theme"


# Information about where the book exists on the web
repository:
  url: https://github.com/Danieljoha/Bed-1304-ressursesside  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

html:
  use_issues_button: true
  use_repository_button: true

parse:
  myst_enable_extensions:
    # Defaults here: https://jupyterbook.org/en/stable/customize/config.html
    - html_image
    - amsmath
    - dollarmath



# execute:
#   timeout: -1 # Disable timeouts for executing notebooks
