---
title: '[< Forrige](4%20-%20lister_oppslag_numpy.ipynb)     |     [Neste >](6%20-%20Logikk_l칮kker.ipynb)'
jupyter: python3
---



<span style="color:#9bb1d4;font-size:30px;font-weight:900"> 5 - Pandas og databehandling </span>  

# **Pandas** - et verkt칮y for behandling og lasting av data
I denne delen skal vi utforske hvordan du kan bruke Pandas til 친 h친ndtere og modifisere data. Vi skal ogs친 g친 gjennom grunnleggende databehandling, filtrering, aggregering og visualisering.

# 1. Introduksjon til Pandas
Pandas er et kraftig verkt칮y for datah친ndtering og analyse. Det gir deg muligheten til 친 arbeide med datasett som er representert som DataFrames, en struktur som ligner regneark som dere kanskje kjenner fra Excel.

Men f칮rst, som alle pakker i Python, m친 vi laste den inn f칮rst.

F칮rst, hvis vi ikke har gjort det, bruker vi ```pip install``` for 친 laste ned pandas. Det kan gj칮res ved 친 skrive f칮lgende:

```python
        # Laster ned pandas med pip
        !pip install pandas
```

S친 m친 vi importere modulen, at vi "henter" den klar for bruk, ved 친 kj칮re cellen under: 

```{python}
import pandas as pd
```

## **Eksempel: Importere Pandas og laste inn en CSV-fil**
Det gj칮r vi ved 친 skrive f칮lgende:

```python
        # Laste inn en CSV-fil som et DataFrame
        data = pd.read_csv('data/eksempel_data.csv')

        # Vise de f칮rste radene i DataFrame
        data.head()
```

MEN! Her er det viktig 친 huske p친 at *'data/eksempel_data.csv'* m친 v칝re *banenavn* til filen du 칮nsker 친 lese. Den er alts친 unik for din PC/MAC.

**OBS!** En del Windows brukere m친 skrive en `r` (som st친r for *read*) foran `'data/eksempel_data.csv'`, alts친 slik `data = pd.read_csv(r'data/eksempel_data.csv')`, s친 pr칮v det om du f친r feilmelding.

```{python}
# Laste inn en CSV-fil som et DataFrame
data = pd.read_csv('DERES_PATH/schooling-gdp.csv')

### OBS: F칀R DU FEILMEDLING OVER, SJEKK AT FILBANEN ER RIKTIG TIL DIN MAC/PC!!! ###

# Vise de f칮rste radene i DataFrame
data.head()
```

Vi ser at vi har fire variabler: `Land`, `Landkode`, `BNP_per_capita` (BNP per innbygger), `Utdanning` og `Befolkning`. BNP er "brutto nasjonalprodukt" som m친ler hvor mye som produseres i et land i l칮pet av et 친r. `BNP_per_capita` viser alts친 hvor mye hver person i landet produserer hvert 친r i gjennomsnitt.  

Import av data til `pandas` gj칮res enkelt med funksjonen `read_csv`. Dersom du har lastet ned siste versjon av notebooks, ligger den en fil i mappen "data" som heter schooling-gdp.csv. (kilde: [Our World In Data](https://ourworldindata.org/grapher/correlation-between-mean-years-of-schooling-and-gdp-per-capita)). Denne filen inneholder data om BNP (bruttonasjonalprodukt) og utdanningsniv친 for ulike land i 2010.

## **Operasjoner p친 dataframe's**
Vi antar at vi har kalt *dataframen* (norsk: *dataramme*) for ```data``` (som over). 

Her er en liste av operasjoner vi kan gj칮re for 친 inspisere, endre og bli kjent med data'en v친r ved hjelp av Pandas. Denne kan v칝re et fint oppslagsverk for hva dere kan trenge om Pandas. Dokumentasjon om dette finnes ogs친 [her](https://pandas.pydata.org/docs/) og over "hele" Google!

| **Operasjon**                          | **Form친l**                                                     | **Syntaks i Python**                                |
|----------------------------------------|----------------------------------------------------------------|-----------------------------------------------------|
| Vise kolonneoverskriftene              | Viser navnene p친 kolonnene i DataFrame                         | `data.columns`                                      |
| Velge en spesifikk kolonne             | Hente data fra en spesifikk kolonne                            | `data['kolonnenavn']`                               |
| Filtrere rader basert p친 betingelse     | Filtrere data der en betingelse er oppfylt                     | `data[data['Utdanning'] > 10]`                     |
| Sjekke manglende verdier               | Sjekker om det finnes manglende verdier i datasetet            | `data.isnull().sum()`                               |
| Fylle manglende verdier                | Fyller inn manglende verdier med en gitt verdi                 | `data.fillna(0, inplace=True)`                      |
| Beskrivelse av numeriske verdier        | Gir en statistisk oversikt over numeriske kolonner             | `data.describe()`                                  |
| Sortere data (stigende)                | Sorterer data etter en kolonne i stigende rekkef칮lge            | `data.sort_values('kolonnenavn', ascending=True)`  |
| Se datatyper                           | Viser datatypene til hver kolonne                              | `data.dtypes`                                       |
| Konvertere datatype                    | Endrer datatype for en spesifikk kolonne                       | `data['kolonne'] = data['kolonne'].astype(float)`   |
| Lese fra Excel-fil                     | Leser data fra en Excel-fil                                    | `data = pd.read_excel('filnavn.xlsx')`              |
| Ny kolonne med beregninger             | Oppretter en ny kolonne som er et resultat av beregninger       | `data['new_column'] = data['kolonne1'] / data['kolonne2']` |
| Finne duplikater                       | Sjekker om det finnes dupliserte rader                         | `data.duplicated()`                                 |
| Fjerne duplikater                      | Fjerner dupliserte rader                                       | `data.drop_duplicates(inplace=True)`                |
| Histogram                              | Lager et histogram for en spesifikk kolonne                    | `data['kolonnenavn'].plot(kind='hist')`             |
| Konvertere til datetime                | Konverterer en kolonne til datetime-objekter                   | `data['dato'] = pd.to_datetime(data['dato'])`       |
| Informasjon av datarammen              | Oppsummere hva datarammen er og best친r av                      | `data.info()`                                       |
| Velger rader med **loc**               | Velge rader basert p친 etiketter (navn)                         | `data.loc[2, 'Navn']`                               |
| Velger rader med **iloc**              | Velge rader basert p친 indeksnummer                             | `data.loc[2, 1]`                                    |
| "Merge" to DataFrames                  | Kombinere to DataFrames basert p친 en felles kolonne            | `df3 = df1.merge(df2, on='ID', how='inner')`        |
| Oppsummerende statistikker             | Gir spesifikke beregninger som gj.snitt, median, maks, osv.       | `data['kolonne'].mean()` eller `data['kolonne'].median()`  |




... og det er mange, mange fler. Det vil dere f친 testa dere p친 gjennom oppgavene. Kommer du over et problem du ikke har sett f칮r, pr칮v 친 google det. 

Lurer du p친 noe, s친 har noen lurt p친 det samme f칮r deg :-)

## Eksempelbruk av operasjoner p친 dataframe's
Siden vi allerede har kj칮rt kodeblokken over, har vi variabelen ```data```, som inneholder dataframe'n med data fra 'schooling-gdp.csv'-filen v친r.

```{python}
# 1. Viser kolonneoverskriftene
print(data.columns)
```

Her ser i at vi f친r navn p친 alle kolonnene i dataframe'n v친r. Nyttig inspeksjon!

```{python}
# 2. Velg en spesifikk kolonne (BNP per capita)
bnp_column = data['BNP_per_capita']
print(bnp_column)
```

Her ser vi verdiene for kolonnen `BNP_per_capita`, vi ser kolonnens `Name`, `Length` (alts친 hvor mange tall) og 'dtype' (her har vi et flyttall (float)).

```{python}
# 3. Filtrer rader basert p친 en betingelse (land med utdanning > 10 친r)
high_education = data[data['Utdanning'] > 10]
print(high_education)
```

Her f친r vi listet opp alle landene som har at `Utdanning` er over 10 친r.

```{python}
# 4. Sjekke om det finnes noen manglende verdier (ogs친 kalt: NAN - Not a Number)
missing_values = data.isnull().sum()
print(missing_values)
```

Denne koden sjekker om det er manglende verdier i datasettet v친rt. Her er det '0' i alle kolonnene, som betyr at det er data i alle cellene i dataframe'n, men jobber man med ekte data - trenger det slett ikke v칝re tilfelle.

```{python}
# Alternativt til 4.
data.isna()
data.isna().sum()
```

```{python}
# 5. Fyll manglende verdier (hvis det var noen) med 0
data.fillna(0, inplace=True)
```

Koden over vil fulle inn '0' der det er manglende verdier. Men det kan godt tenkes man burde ta gjennomsnitt, median eller en annen verdi her. Det vil avhenge av datasettet man har.

```{python}
# 6. Beskrivelse av numeriske verdier
description = data.describe()
print(description)
```

Her f친r vi en beskrivelse av de numeriske verdiene i dataframe'n. 

```{python}
# 7. Sortere data etter BNP per capita (stigende)
sorted_data = data.sort_values('BNP_per_capita', ascending=True)
print(sorted_data)
```

Her har vi sortert data'en i stigende rekkef칮lge, basert p친 variablen `BNP_per_capita`. Hadde vi satt ```ascending=False```, ville det v칝re i synkende rekkef칮lge!

```{python}
# 8. Se datatypene
data_types = data.dtypes
print(data_types)
```

Her ser vi datatypene til kolonnene v친re.

```{python}
# 9. Konvertere en kolonne til en annen datatype (Befolkning til float)

data['Befolkning'] = data['Befolkning'].astype(float)
data['Befolkning']
```

Her ser vi at vi gjorde om `Befolkning` fra heltall ('int64') til flyttall ('float64'). 

**OBS:** Men pr칮v 친 tenk over hva vi akkurat gjorde - gir det mening 친 ha `Befolkning` variabelen som flytall (desimaltall)?

```{python}
# 10. Ny kolonne som er en funksjon av andre kolonner (BNP total)
data['BNP_total'] = data['BNP_per_capita'] * data['Befolkning']
print(data)
```

Her lager vi en ny kolonner, som en funksjon av de to andre kolonnene, BNP og Befolkning.

```{python}
# 11. Finne dupliserte rader
duplicates = data.duplicated()
print(duplicates)

# Her summerer vi 'duplicates' - husk at False = 0, True = 1
# s친 hvis summen er lik '0' - s친 betyr det at det ikke er duplikater.
print(sum(duplicates))
```

Her leter vi etter duplikater i data'en v친r. Her ser alt ut til 친 v칝re 'False' --> alts친, ingen duplikater.

Legg merke til at ```print(duplicates)``` viser 'False' for de f칮rste fem, og de siste 5 radene i dataframe'n. Men vanskelig 친 si noe om de mellom indeks 4 og indeks 101.

Derfor har jeg skrevet ```print(sum(duplicates))```, for vi husker fra tidligere forelesning. S친 behandles 'False' som tallet $0$ og 'True' som tallet $1$.

```{python}
# 12. Fjerne duplikater
data.drop_duplicates(inplace=True)
```

Hadde vi hatt duplikater (noe vi ikke har her), hadde vi n친 fjernet dem! :-) 

```{python}
# 13. Plot et histogram over utdanningsniv친
data['Utdanning'].plot(kind='hist')
```

Her har vi plottet et histogram ved hjelp av 'Pandas'. Hvor vi ser frekvensen av de ulike utdanningstallene. Vi skal l칝re mer om plotting senere i kurset, da det er andre bibliotek (matplotlib og seaborn) som egner seg enda bedre for dette.

```{python}
# 14. Bruke .loc for 친 hente data for et spesifikt land
norway_data = data.loc[data['Land'] == 'Norway']
print(norway_data)
```

```{python}
# 15. Bruke .iloc for 친 hente rader og kolonner basert p친 indeks
subset = data.iloc[0:5, 0:3]  # F칮rste 5 rader, f칮rste 3 kolonner
print(subset)
```

```{python}
# 16. Oppsummerende statistikk over BNP per innbygger
print("Gjennomsnittlig BNP per innbygger:", data['BNP_per_capita'].mean())
print("Median BNP per innbygger:", data['BNP_per_capita'].median())
print("H칮yeste BNP per innbygger:", data['BNP_per_capita'].max())
print("Laveste BNP per innbygger:", data['BNP_per_capita'].min())
```

# **Oppgaver**
Under er det et datasett dere skal lese inn og gj칮re en rekke oppgaver. Bruk notatene over, Pandas dokumentasjon og Google som hjelp. Lykke til! :-)

Vi bruker et datasett som dere finner p친 GitHub under `'/data'` mappen kalt: `'bilparken_ssb.csv'`

## 游늵 Oppgave 1
Les inn csv.-filen som en dataframe ved hjelp av Pandas biblioteket.


## 游늵 Oppgave 2
Skriv en beskrivelse av data'en under her. Bruk kode for 친 inspisere data'en.



## 游늵 Oppgave 3
Sjekk hvilke datatyper vi har i Dataframe'n


## 游늵 Oppgave 4
Sorter datasettet, ```df``` fra oppgave 1, basert p친 variabelen "Personbiler vraket mot pant (prosent av bestanden)" - i synkende rekkef칮lge.

Verifiser at dere fikk dette til.


## 游늵 Oppgave 5
Filtrer rader med h칮yere gjennomsnittsalder ved vraking enn **18 친r**.


Her ser vi at flere 'Bilmerker' har forsvunnet fra dataframe'n - som f.eks. Tesla.

## 游늵 Oppgave 6
Finn gjennomsnittlig `'Personbilbestand 31. desember'` for alle bilmerkene i datasettet.


## 游늵 Oppgave 7
Finn bilmerket med h칮yest gjennomsnittsalder ved vraking.

Tips, her kan der fp bruk for funksjonene:
* ```df.loc```
* ```.idxmax()```

Det kan brukes slik:
```python
# Dette gj칮r at vi kan finne raden hvor h칮yeste verdien av 'kolonne_av_interesse' er.
df.loc[df['Kolonne_av_interesse'].idxmax()] 
```


Chevrolet er det bilmerke med h칮yest gjennomsnittlig vrakealder!

## 游늵 Oppgave 8 - Statistisk sentralbyr친
SSB - Statistisk sentralbyr친 sitter mye data. Det er ogs친 en arbeidsplass med mange samfunns칮konomer og bedrifts칮konomer.

Uansett, vi har muligheten til 친 hente data der ifra. Koden under viser hvordan vi henter data fra SSB sitt API. Mer om det kan de interesserte lese [her](https://www.ssb.no/api/pxwebapi/_/attachment/inline/019c05e0-35ad-4757-87a0-ba7fbf4a68e2:397d9112916d85696733b77d376220c4465cb4fb/Api_brukerveiledning.pdf).

```{python}
# hente CSV fra SSB til pandas

# Importerer Python pandas for 친 kunne lage dataframe
import pandas as pd

# pd.read_csv() henter innholdet fra API-et og legger det i data. 
# De norske datasettene her er semikolonseparert med komma som desimaltegn.
# CSV er ikke UTF-8, s친 vi m친 angi parameter encoding for 친 f친 칝칮친 riktig. 

data = pd.read_csv("https://data.ssb.no/api/v0/dataset/1066.csv?lang=no", sep=';', decimal=',', encoding = "ISO-8859-1", )
```

## Oppgave 8a
Her i **Oppgave 8a** skal dere kommentere kodelinjene under, og si noe om hva de gj칮r.

```{python}
#
type(data)
```

```{python}
#
data.shape
```

```{python}
#
data.head()
```

```{python}
#
data['m친ned']= pd.to_datetime(data['m친ned'].str.replace('M', '-'))

#
data.index = data['m친ned']

#
data.info()
```

```{python}
# Se hva som skjedde med 'm친ned' kolonnen n친!
data.head()
```

```{python}
# 
data.plot(x='m친ned', y='07129: Varehandelsindeksen, etter n칝ring, m친ned og statistikkvariabel', figsize=(6, 12), color ='g')

# 
data_serie = data['07129: Varehandelsindeksen, etter n칝ring, m친ned og statistikkvariabel']

# 
data_serie.plot()
```

## Oppgave 8b
Utforsk et annet datasett fra SSB, ved 친 kj칮re dette:
```python
# hente CSV fra SSB til pandas

# Importerer Python pandas for 친 kunne lage dataframe
import pandas as pd

# pd.read_csv() henter innholdet fra API-et og legger det i data. 
# De norske datasettene her er semikolonseparert med komma som desimaltegn.
# CSV er ikke UTF-8, s친 vi m친 angi parameter encoding for 친 f친 칝칮친 riktig. 

ssb = pd.read_csv("https://data.ssb.no/api/v0/dataset/1078.csv?lang=no", sep=';', decimal=',', encoding = "ISO-8859-1", )
ssb
```

Utforsk denne datarammen, ved 친 gj칮re f칮lgende:
1. Last inn data.
2. Se p친 de f칮rste fem radene.
3. Bruk Pandas til 친 f친 informasjon om datarammen.
4. Bruk `ssb.describe()` for 친 beskrive de numeriske kolonnene.
5. Unders칮k unike verdier i hver kolonne.
6. Grupper data etter `region` og `kj칮nn`, og se hvor mange som er i de ulike gruppene.
7. Filtrer spesifikke verdier. F.eks. Kj칮r `ssb[ssb['kj칮nn'] == '2 Kvinner']` - hva f친r du da? Pr칮v 친 filtrere p친 andre ting?
8. Bruk **pandas** til 친 visualisere hvor mange kvinner og hvor mange menn det er i Halden. Du vil f친 bruk for Pandas funksjonene, `groupby()` og `.sum()`.

## 游늵 Oppgave 9 - Eurostat

Eurostat er en veldig nyttig kilde til data. De har et stort utvalg av data p친 europeiske land. De har laget en egen pakke til python som ikke overraskende heter `eurostat`. Denne pakken er heller ikke installert, s친 dere m친 kj칮re  `!pip install eurostat` f칮rst. G친 igjennom de neste *chunkene* med kode, og pr칮v 친 forst친 hva vi gj칮r.

For 친 se hvilke tabeller som er der, henter vi innholdsfortegnelsen (table of contents) med funksjonen `get_toc_df`. Det gir oss en `pandas` dataramme:

#### Laster ned `eurostat` med pip.

```{python}
!pip install eurostat
```

```{python}
#| scrolled: true
import eurostat
toc = eurostat.get_toc_df()
toc
```

Du kan finne hvor mange tabeller det er med `len(toc)`, og det er i skrivende stund er det rundt 8 tusen tabeller. Det blir litt krevende 친 lete gjennom alle, s친 vi 칮nsker derfor 친 begrense antall tabeller til de som er relevante. Anta at vi 칮nsker 친 se p친 utviklingen i BNP per innbygger for landene som er med i statistikken. N칝rmere bestemt, vi 칮nsker 친 finne alle tabeller der `'GDP per capita'` er i tittelen. 

BNP per innbygger er hvor mye hver person i landet i gjennomsnitt produserer i l칮pet av ett 친r. 

Vi gj칮r dette ved 친 lage f칮lgende "list comprehension": `['GDP per capita' in i for i in toc['title']]`. Elementene i denne listen er sant (`True`) dersom 'GDP per capita' er i tittelen, og usant (`false`) om det ikke er i tittelen. 

#### Det gj칮r vi slik:

```{python}
gdp_in_toc_list = ['GDP per capita' in i for i in toc['title']]
```

Vi kan s친 velge de elementene hvor betingelsen er sann ved 친 sette listen inn i en klammeparentes etter innholdsfortegnelsen, `toc[gdp_in_toc_list]`. Kun de elementene i innholdsfortegnelsen der det st친r sant (`True`) i listen, tas da med.

```{python}
# collecting only the tables where 'GDP per capita' is in the name
toc_gdp = toc[gdp_in_toc_list]
toc_gdp
```

La oss n친 se p친 tabellen `"Real GDP per capita"`, som har kode `'TIPSNA40'`. Da bruker vi funksjonen `get_data_df` med tabellkoden som argument: 


#### Laster inn denne tabellen

```{python}
gdp_data = eurostat.get_data_df('TIPSNA40')
gdp_data
```

## **Oppgave 9a - Jobbe med data**
Du har f친tt utdelt et datasett `gdp_data` som inneholder BNP per innbygger (GDP per capita) for ulike europeiske land over flere 친r. Dataene har noen utfordringer, som manglende verdier (NaN) og kolonner som ikke er relevante for analysen.

M친let med oppgaven er 친:

* Rydde opp i dataene ved 친 fjerne un칮dvendige kolonner og h친ndtere eventuelle manglende verdier.
* Ekstrahere data kun for Italia (IT), Danmark (DK) og Sverige (SE).
* Transformere dataene slik at 친rstallene blir kolonner, og vi har et rent format.
* Utf칮re beskrivende statistikk og visualisere utviklingen i BNP per capita for de tre landene.
* Bruke standard pandas-metoder for 친 utforske dataene videre.

##  游댃 Del 1: Rens og filtrer data
1. Last inn datasettet i en pandas DataFrame.
2. Fjern un칮dvendige kolonner (f.eks. `freq`, `unit`, `na_item`).
3. Behold kun rader for Italia (IT), Danmark (DK) og Sverige (SE).
4. Sjekk og h친ndter eventuelle manglende verdier (`NaN`).


## 游댃 Del 2: Transform칠r data

1. Sett opp DataFrame slik at:
   - `geo\TIME_PERIOD` blir indeks.
   - 칀rstallene blir kolonnenavn.
   - BNP per capita-verdiene for hvert land forblir i tabellen.
2. Konverter eventuelle verdier som er lagret som `object` til `float`.


## 游늵 Del 3: Videre analyse av data

1. Beregn beskrivende statistikk for hvert av landene:
   - Gjennomsnitt, median, standardavvik.
   - Maksimum og minimum BNP per capita.
2. Finn ut hvilket 친r hvert land hadde h칮yest BNP per capita.




##### [< Forrige](4%20-%20lister_oppslag_numpy.ipynb)     |     [Neste >](6%20-%20Logikk_l칮kker.ipynb)

